services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"


script:
  - docker --version
# Building  the api-feed docker image IM 1
  - docker build -t udagram-api-feed ./udagram-api-feed

# Tagging
  - docker tag udagram-api-feed johnnkanu/udagram-api-feed:latest

after_success:
# Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push johnnkanu/udagram-api-feed

script:
  - docker --version
# Building the api-user IM 2

  - docker build -t udagram-api-user ./udagram-api-user

# Tagging
  - docker tag udagram-api-user johnnkanu/udagram-api-user:latest

after_success:
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push johnnkanu/udagram-api-user



script:
  - docker --version
# Building the frontend docker image IM 4

- docker build -t udagram-frontend ./udagram-frontend

# Tagging
- docker tag udagram-frontend johnnkanu/udagram-frontend:latest

after_success:
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push johnnkanu/udagram-frontend


script:
  - docker --version
# Building the reverseproxy docker image IM 4

  - docker build -t reverseproxy ./reverseproxy

# Tagging
  - docker tag reverseproxy johnnkanu/reverseproxy:latest

after_success:
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push johnnkanu/reverseproxy
